///////////////////////////////////////////////////////////
//  App.cs
//  Implementation of the Class App
//  Generated by Enterprise Architect
//  Created on:      28-Mar-2016 9:30:09 AM
//  Original author: Moshe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Windows;

namespace Zave
{
    /// <summary>
    /// Interaction logic for App.xaml
    /// </summary>
    public partial class App : Application
    {

        /// <summary>
        /// Prototype hardcoded ZDF for early version
        /// </summary>
        public ZaveViewModel.ZDFEntryViewModel.ZDFEntryViewModel activeZDFEntry { get; set; }

        

        /// <summary>
        /// Runs Init() Method
        /// </summary>
        public App()
        {
            Init();


        }

        ~App()
        {

        }

        /// <summary>
        /// Runs Debug code. Right now, creates a ZDF to work with.
        /// </summary>
        public void Init()
        {
            
            activeZDFEntry = new ZaveViewModel.ZDFEntryViewModel.ZDFEntryViewModel();
        }

    }//end App

}//end namespace ZaveProject