///////////////////////////////////////////////////////////
//  App.cs
//  Implementation of the Class App
//  Generated by Enterprise Architect
//  Created on:      28-Mar-2016 9:30:09 AM
//  Original author: Moshe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Windows;

namespace Zave
{
    /// <summary>
    /// Interaction logic for App.xaml
    /// </summary>
    public partial class App : Application
    {

        Zave.ZDF.ZDF activeZDF { get; set; }


        public App()
        {
            this.Init();
        }

        ~App()
        {

        }

        public void Init()
        {
            activeZDF = new Zave.ZDF.ZDF();
        }

    }//end App

}//end namespace ZaveProject