///////////////////////////////////////////////////////////
//  App.cs
//  Implementation of the Class App
//  Generated by Enterprise Architect
//  Created on:      28-Mar-2016 9:30:09 AM
//  Original author: Moshe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Windows;
using ZaveViewModel.ZDFViewModel;
using ZaveController.Global_Settings;
using ZaveGlobalSettings.ZaveFile;
using Prism.Events;
using Microsoft.Practices.Unity;

namespace Zave
{
    /// <summary>
    /// Interaction logic for App.xaml
    /// </summary>
    public partial class ZaveApp : Application
    {



        EventInitSingleton eventInit;
       

        /// <summary>
        /// Runs Init() Method
        /// </summary>
        public ZaveApp()
        {
            //Init();
            //MainWindow app = new MainWindow();
            //ZDFEntryViewModel viewModel = new ZDFEntryViewModel();
            //app.DataContext = viewModel;
            //app.Show();


        }

        ~ZaveApp()
        {

            if(eventInit != null)
                eventInit.Dispose();

            string projFile = System.IO.Path.GetTempPath() + GuidGenerator.getGuid();
            
            int maxAttempts = 20;
            int retryMilliseconds = 100;
            
            for (int attempts = 0; attempts <= maxAttempts; attempts++)
            {
                try
                {
                    File.Delete(projFile);

                }
                catch (IOException iox)
                {
                    if (attempts == maxAttempts)
                    {
                        throw iox;
                    }
                    System.Threading.Thread.Sleep(retryMilliseconds);
                    
                }
               
            }
        }

        private void Application_Startup(object sender, StartupEventArgs e)
        {
            var bs = new BootStrapper();
            bs.Run();
            IEventAggregator eventAgg = bs.Container.Resolve(typeof(IEventAggregator)) as EventAggregator;

            

            

            eventInit = EventInitSingleton.GetInstance(eventAgg);
            string projFile = System.IO.Path.GetTempPath() + GuidGenerator.getGuid();
            using (StreamWriter sw = StreamWriterFactory.createStreamWriter(projFile))
            {
                try
                {
                    sw.Write("[]");
                    sw.Close();
                }
                catch (IOException ex)
                {
                    throw ex;
                }
            }
            
        }

        

        

    }//end App

}//end namespace ZaveProject