///////////////////////////////////////////////////////////
//  ColorCategory.cs
//  Implementation of the Class ColorCategory
//  Generated by Enterprise Architect
//  Created on:      28-Mar-2016 9:30:09 AM
//  Original author: Moe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Drawing;






namespace ZaveModel.Colors {
    public class ColorCategory{

        public ColorCategory(Color col) {
            Color = col;
        }

        ~ColorCategory() {

        }

        private Color Color;

        public Color getColor()
        {
            return Color;
        }

        public void setColor(System.Drawing.Color col)
        {
            Color = col;
        }

        public void setColor(System.Windows.Media.Color col)
        {
            Color = Color.FromArgb(col.A, col.R, col.G, col.B);
        }



    }//end ColorCategory
}