///////////////////////////////////////////////////////////
//  ColorCategory.cs
//  Implementation of the Class ColorCategory
//  Generated by Enterprise Architect
//  Created on:      28-Mar-2016 9:30:09 AM
//  Original author: Moe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Drawing;
using WPFColor = System.Windows.Media.Color;






namespace ZaveModel.Colors {
    public class ColorCategory{

        private ColorCategory(Color col) {
            Color = col;
        }

        public ColorCategory(Color col, String name) : this(col)
        {
            Name = name;
        }

        ~ColorCategory() {

        }


        public Color Color
        {
            get;
            set;
        }

        public String Name
        {
            get;
            set;
        }

        public WPFColor toWPFColor()
        {
            WPFColor wCol = WPFColor.FromArgb(Color.A, Color.R, Color.G, Color.B);
            return wCol;
        }

        public void FromWPFColor(WPFColor wCol)
        {
            try
            {
                Color = Color.FromArgb(wCol.A, wCol.R, wCol.G, wCol.B);
               
                Name = GetWPFColorName(wCol);
            }
            catch(System.Data.ObjectNotFoundException onf)
            {
                System.Windows.Forms.MessageBox.Show("The Specified Color Could Not Be Found", "Color Not Found", System.Windows.Forms.MessageBoxButtons.OKCancel, System.Windows.Forms.MessageBoxIcon.Warning);
            }


        }

        public ColorCategory ParseFromString(string str)
        {
            ColorConverter converter = new ColorConverter();
            Color = (Color)converter.ConvertFromString(str);
            Name = str;
            return this;

        }

        private string GetWPFColorName(WPFColor color)
        {
            Type colors = typeof(System.Windows.Media.Colors);
            foreach (var prop in colors.GetProperties())
            {
                if (((System.Windows.Media.Color)prop.GetValue(null, null)) == color)
                    return prop.Name;
            }

            throw new System.Data.ObjectNotFoundException("The provided Color is not named.");
        }






    }//end ColorCategory
}