///////////////////////////////////////////////////////////
//  IZDFEntry.cs
//  Implementation of the Interface IZDFEntry
//  Generated by Enterprise Architect
//  Created on:      28-Mar-2016 9:30:09 AM
//  Original author: Moshe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel;
using ZaveModel.Colors;
using ZaveGlobalSettings.Data_Structures;
using Prism.Mvvm;


namespace ZaveModel.ZDFEntry {
	public interface IZDFEntry : INotifyPropertyChanged {

        //event EventHandler<ZaveGlobalSettings.Data_Structures.ModelEventArgs> PropertyChanged;



        ColorCategory HColor
        {
            get;
            set;
        }

        //ZaveGlobalSettings.Data_Structures.SelectionState Source
        //{
        //    get;
        //    set;
        //}

        string Page
        {
            get;
            set;
        }

        string Name
        {
            get;
            set;
        }

        string Text
        {
            get;
            set;
        }

        DateTime DateModified
        {
            get;
            set;
        }

        SrcType Format
        {
            get;
            set;
        }

        int ID
        {
            get;
        }

        SelectionState toSelectionState();



    }//end IZDFEntry

}//end namespace ZDFEntry