///////////////////////////////////////////////////////////
//  ISource.cs
//  Implementation of the Interface ISource
//  Generated by Enterprise Architect
//  Created on:      28-Mar-2016 9:30:09 AM
//  Original author: Moe
///////////////////////////////////////////////////////////

using System;

namespace ZaveModel.ZDFEntry {
	public abstract class Source  {

        

        public Source(string name, string page, string text)
        {
            
            
            DocName = name;
            DocPage = page;
            DocText = text;
            
        }

        

		public String DocName{
			get;
			set;
		}

		public String DocPage{
			get;
			set;
		}

		public String DocText{
			get;
			set;
		}


	}//end ISource

}//end namespace ZDFEntry