///////////////////////////////////////////////////////////
//  ZDFEntry.cs
//  Implementation of the Interface IZDFEntry
//  Generated by Enterprise Architect
//  Created on:      28-Mar-2016 8:22:27 AM
//  Original author: Moshe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel;
using System.Linq;
using ZaveModel.GlobalSettings;
using ZaveModel.ZDFSource;



namespace ZaveModel.ZDFEntry {

    public class ZDFEntry : IZDFEntry
    {



        public List<Comment.IEntryComment> m_IEntryComment;

        public ZDFEntry()
        {

        }

        public ZDFEntry(Source src)
        {
            Source = src;
        }

        ~ZDFEntry()
        {

        }



        public ColorCategory HColor
        {
            get;
            set;
        }

        public Source Source
        {
            get;
            set;
        }


        public string Title
        {
            get;
            set;
        }




    }

        //end ZDFEntry//end IZDFEntry

       

}//end namespace ZDFEntry