///////////////////////////////////////////////////////////
//  ZDFEntry.cs
//  Implementation of the Interface IZDFEntry
//  Generated by Enterprise Architect
//  Created on:      28-Mar-2016 8:22:27 AM
//  Original author: Moshe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel;
using GlobalSettings;
using ZaveModel.ZDFSource;



namespace ZDFEntry {

    public class ZDFEntry : IZDFEntry, INotifyPropertyChanged {

        private GlobalSettings.ICategory hColor;
        private string title;
        public List<IEntryComment> m_IEntryComment;

        public ZDFEntry() {

        }

        ~ZDFEntry() {

        }

        public ICategory HColor {
            get {
                return hColor;
            }
            set {
                hColor = value;

            }
        }

        private Source source;
        public Source Source {
            get { return source; }
            set
            {
                source = value;
                OnPropertyChanged("Source");

            }
        }

        public string Title {
            get {
                return title;
            }
            set {
                title = value;

            }
        }

        //end ZDFEntry//end IZDFEntry

        #region INotifyPropertyChanged Members
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        private void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this,
                    new PropertyChangedEventArgs(propertyName));
            }
        }
        #endregion
    }

}//end namespace ZDFEntry