///////////////////////////////////////////////////////////
//  Source.cs
//  Implementation of the Class Source
//  Generated by Enterprise Architect
//  Created on:      28-Mar-2016 9:30:09 AM
//  Original author: Moe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ZDFSource {
	public class Source {

		public Source(){

		}

		~Source(){

		}

	}//end Source

}//end namespace ZDFSource