///////////////////////////////////////////////////////////
//  WordSource.cs
//  Implementation of the Class WordSource
//  Generated by Enterprise Architect
//  Created on:      28-Mar-2016 9:30:09 AM
//  Original author: Moshe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

using ZaveModel.ZDFSource;

namespace ZaveWordAddin.ZDFSource {
	public class WordSource : Source
    {

        ZaveSourceAdapter.Data_Structures.SrcType srcType { get; }

        public WordSource(string name, string page, string text) : base(name, page, text){
            srcType = ZaveSourceAdapter.Data_Structures.SrcType.WORD;
		}

		~WordSource(){

		}

       

	}//end WordSource

}//end namespace ZDFSource