///////////////////////////////////////////////////////////
//  IZDFEntry.cs
//  Implementation of the Interface IZDFEntry
//  Generated by Enterprise Architect
//  Created on:      28-Mar-2016 9:30:09 AM
//  Original author: Moshe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ZDFEntry {
	public interface IZDFEntry  {

	}//end IZDFEntry

}//end namespace ZDFEntry