///////////////////////////////////////////////////////////
//  ColorCategory.cs
//  Implementation of the Class ColorCategory
//  Generated by Enterprise Architect
//  Created on:      28-Mar-2016 9:30:09 AM
//  Original author: Moe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;





namespace ZaveModel.GlobalSettings {
    public class ColorCategory{

        public ColorCategory() {

        }

        ~ColorCategory() {

        }

    }//end ColorCategory
}