///////////////////////////////////////////////////////////
//  MainWindow.cs
//  Implementation of the Class MainWindow
//  Generated by Enterprise Architect
//  Created on:      28-Mar-2016 9:30:09 AM
//  Original author: Moshe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Windows;

namespace ZaveProject {
	/// <summary>
	/// Interaction logic for MainWindow.xaml
	/// </summary>
	public partial class MainWindow : Window {



		~MainWindow(){

		}

		public MainWindow(){

		}

		/// 
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void button_Click(object sender, RoutedEventArgs e){

		}

	}//end MainWindow

}//end namespace ZaveProject